package be.faros.flags.domain;

public enum BasicLayerType {
    FIELD, PER_PALE, PER_FESS, PER_BEND, PER_BEND_SINISTER, PALE, FESS, BEND, BEND_SINISTER, SIDE, SIDE_SINISTER, CHIEF, BASE, PER_CROSS, PER_SALTIRE, COUPED_CROSS, SYMMETRIC_CROSS, NORDIC_CROSS, SALTIRE, CANTON, BORDURE, PILE, PILE_THROUGHOUT, CHEVRON, PALL, ARROWHEAD, GUSSET, STRIPES
}
